CREATE LOGIN [bit-erp\jenkins] FROM WINDOWS;  
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [bit-erp\jenkins];
GO

CREATE LOGIN [.\USR1CV8] FROM WINDOWS;  
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [.\USR1CV8];
GO